# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "socialsharing"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/socialsharing"

[[annotations]]
path = ["**/l10n/**.js", "**/l10n/**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 Nextcloud translators"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**/.tx/config"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["**/composer.json", "**/composer.lock", "**/package.json", "**/package-lock.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "socialsharing_email/img/app.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2024 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["socialsharing_diaspora/img/app.svg", "socialsharing_diaspora/img/diaspora.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Diaspora"
SPDX-License-Identifier = "LicenseRef-DiasporaTrademarks"

[[annotations]]
path = ["socialsharing_facebook/img/app.svg", "socialsharing_facebook/img/facebook.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Meta"
SPDX-License-Identifier = "LicenseRef-FacebookTrademarks"

[[annotations]]
path = ["socialsharing_telegram/img/app.svg", "socialsharing_telegram/img/telegram.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Telegram"
SPDX-License-Identifier = "LicenseRef-TelegramTrademarks"

[[annotations]]
path = ["socialsharing_twitter/img/app.svg", "socialsharing_twitter/img/x.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 X Corp."
SPDX-License-Identifier = "LicenseRef-XTrademarks"

[[annotations]]
path = ["socialsharing_whatsapp/img/app.svg", "socialsharing_whatsapp/img/whatsapp.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Meta"
SPDX-License-Identifier = "LicenseRef-WhatsappTrademarks"

[[annotations]]
path = ["socialsharing_bluesky/img/app.svg", "socialsharing_bluesky/img/bluesky.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Bluesky, PBC"
SPDX-License-Identifier = "LicenseRef-BlueskyTrademarks"
